### ISSUE TITLE
bootstrap.min.js missing?

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#1]
I'm getting this error in the console:

```
http://shiffman.net/learningprocessing.com/js/bootstrap.min.js 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

bootstrap.js is there, but not bootstrap.min.js.  I would add it myself but wanted to check with you @scottwooden first.

**Comment by scottwooden** [comment]
We don't need bootstraip.min. Can't actually find where it's referencing it?

**Comment by shiffman** [comment]
oh this is from a while ago, not showing anymore
