### ISSUE TITLE
code width

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#15]
The code is often sometimes too wide for space allotted.  Possible solution is a button top right of the code window that signifies expand, and when clicked it, the code window increases width say 70% of the window width, and the sketch is overlaid under it?

**Comment by shiffman** [comment]
Actually another solution to this is to just not wrap the code, and users can scroll to the right if some lines are too long.  This is how an IDE behaves so maybe this is simplest.

**Comment by scottwooden** [comment]
Yeah I think this is a nice easy solution for now. I've added this in fairly primitively for now. Need to do some javascript to keep containers looking neat.

**Comment by shiffman** [comment]
I'm happy with this so closing.
