### ISSUE TITLE
setTimeout for moving canvas doesn't always work

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#2]
maybe need to load things in order properly?

<img width="1192" alt="screen shot 2015-08-12 at 10 40 22 am" src="https://cloud.githubusercontent.com/assets/191758/9226867/9e27a5e8-40de-11e5-9054-dbcda9185545.png">

**Comment by scottwooden** [comment]
Yeah need to figure this one was a quick fix for now!

**Comment by scottwooden** [comment]
Still trying to figure this out. Not sure why it's getting executed before... I'll continue to investigate but if you find a solution let me know!

**Comment by shiffman** [comment]
I'll take a look at this too.

**Comment by shiffman** [comment]
Testing with this, stay tuned:

https://gist.github.com/shiffman/22bb21705ce2829207b1

**Comment by shiffman** [comment]
Ok, looks like solution is:

``` javascript
  <script language="javascript">
    window.onload = function() {
      $('#defaultCanvas').appendTo("#sketch-container");
    };
  </script>
```

Need to find best place to interject.

**Comment by scottwooden** [comment]
Cool! Did you want to implement that or shall I pop it in?

**Comment by shiffman** [comment]
Feel free to go ahead! Or I will later, either way ok.

**Comment by shiffman** [comment]
added with bb2167c36d60a01d7b94403b14237ac58fa8da6f, @scottwooden feel free to move things around as needed.
