### ISSUE TITLE
video pages add "watch on youtube" link/button

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#20]
I will add this to the post, i.e.

```

---
layout: videos
title: Built-in variables (mouseX,mouseY)
permalink: /videos/3-1
chapter: 3.1
video: http://player.vimeo.com/video/71597763
youtube: https://www.youtube.com/watch?v=2VLaIr5Ckbs
etc.
--- 
```

**Comment by scottwooden** [comment]
I've added a youtube link on the video page

**Comment by shiffman** [comment]
Working and tested with http://learningprocessing.com/videos/0-0/.  Re-assigning to myself, need to add all the actual links now.

**Comment by shiffman** [comment]
I have actually changed all the embeds to youtube and the "view on" now points to vimeo.  Closing this but will re-open a new issue regarding annotations working with youtube.
