### ISSUE TITLE
sketches that reference media don't work

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#23]
For example see:

http://learningprocessing.com/examples/chp15/example-15-01-drawimage/

This has to do with how we are pulling the JS code from github as a CDN.  I might just have to duplicate these examples on the site or come up with another clever solution.

**Comment by scottwooden** [comment]
Ah yes I see, is there a way to modify the script to strip the url and attach the actual path before the image name? Just spit balling ideas you probably have a better solution!

**Comment by shiffman** [comment]
Ok, I'm just manually editing these examples to work with files stored in `/code/assets/` for now.  Closing and may re-visit later.
