### ISSUE TITLE
Exercises not showing up

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#26]
Not seeing them on "Exercise page", but something is showing up (just not right) on specific permalinks.  I might have screwed something up adding all the _posts.

http://learningprocessing.com/exercises/
http://learningprocessing.com/exercises/chp01/exercise-01-01-shapes/

**Comment by scottwooden** [comment]
All the exercise posts, have "group: example" needs to be "group:exercise"

**Comment by scottwooden** [comment]
Also. Any reason why some sketch.js files aren't being pulled in? For instance, the example top now pulls in .pde. but fails to pull in sketch.js

https://cdn.rawgit.com/shiffman/LearningProcessing-p5.js/master/chp01_drawing/exercise_01_01_shapes/sketch.js

is not found

**Comment by shiffman** [comment]
Exercise group is fixed.  Looking into the sketch.js stuff and wile file separately

**Comment by shiffman** [comment]
I had an extra slash by accident, fixed now with c54c64a073136ffd397b2efd1688c97607151e68!
