### ISSUE TITLE
Video navigation 

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#27]
1. sorting
2. use hyphen instead of dot

any other design cleanup?

**Comment by shiffman** [comment]
changed dot to hyphen with 0726b48abfdfaa8e791d4caa7f7d772f6410fcbf

**Comment by scottwooden** [comment]
This seems fine to me now apart from the nav which is in another github issue right?

**Comment by shiffman** [comment]
That's right, yes!
