### ISSUE TITLE
footer with reference to p5.js for sketches running with link to p5.js code?

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#3]

**Comment by scottwooden** [comment]
Done on exercise and example page

**Comment by shiffman** [comment]
This looks great but the "fork me on github" link is now confusing.  Since it's right below "sketch made with p5.js" it feels like that should link to p5.js code.  I wonder if we can get "SKETCH RUNNING VIA P5.jS" to link to both p5js.org as well as https://github.com/shiffman/LearningProcessing-p5.js.  And then move the "fork me on github" to somewhere else?   Also, maybe "fork me" isn't the right language for this site and "site hosted via github pages" with a link to the repo is better.  That would actually clear up the confusion too.  Sorry to ramble.

**Comment by shiffman** [comment]
Oh, also, now that I think of it. . we should link to github where the PDE code is stored too. Like "fork this on github" or "see this code on github" or something more elegant.  So now we have:
1. Something saying the sketch runs via p5js with link to p5js.org.
2. Something linking to p5.js version of sketch on github.
3. Something linking to the Processing source on github.
4. A general note that the site is hosted via github pages.

Not sure if this is too much, all of this is not necessarily needed.

**Comment by scottwooden** [comment]
Okay made a few changes on this. I think the best way is:

Leave the "Website on Github" link on the homepage.

Then each example / excercise sketch has on the bottom right:

SKETCH RUNNING VIA P5.JS
JS CODE / PDE CODE ON GITHUB

With the code being clickable.

What do you think?

**Comment by shiffman** [comment]
Yes, this sounds great, thanks!
