### ISSUE TITLE
"no sketch available" alternatives

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#30]
Examples or exercises that don't have a running sketch could have a image (screenshot) and/or text explanation instead.  Not sure where to add this?

**Comment by scottwooden** [comment]
Yeah okay, that sounds good. If you added this to our post format. I guess something like "sketch-alternative" then I can detect accordingly.

**Comment by shiffman** [comment]
Related to this, what about a flag for "no sketch or alternative either"?  For example, this one it would fit / look better with just no right area?

http://learningprocessing.com/examples/chp04/example-04-01-declaringvars/

**Comment by scottwooden** [comment]
How about a "Code-only" attribute that was true or false.. if true, the grey window shrinks down considerably.

**Comment by shiffman** [comment]
Perfect.  I've added the code only attribute for Example 4-01 for testing. https://github.com/shiffman/learningprocessing.com/commit/f9ee89d6a5e949f3e80fcedc14f08a0ff122ac77

**Comment by shiffman** [comment]
Will work on finding an example that needs a screenshot or some other text soon.

**Comment by shiffman** [comment]
@scottwooden, is this correct in `2015-08-15-example-04-01-declaringvars.html`?

https://github.com/shiffman/learningprocessing.com/blob/gh-pages/_posts/examples/2015-08-15-example-04-01-declaringvars.html#L16

**Comment by scottwooden** [comment]
Added ability to handle code-only attribute. It will now shrink the grey area and expand the code window

**Comment by shiffman** [comment]
The "code-only" attribute is working great.  I've now also added an example referencing a PNG and caption rather than a p5.js sketch.  The example should load the PNG rather than a canvas in the same spot.

https://github.com/shiffman/learningprocessing.com/blob/gh-pages/_posts/examples/2015-08-15-example-19-03-broadcasting-server.html
http://learningprocessing.com/examples/chp19/example-19-03-broadcasting-server/

**Comment by scottwooden** [comment]
Done. Now pulls in image and sketch annotation

**Comment by shiffman** [comment]
Working great, the rest will be resolved via #39 and #40
