### ISSUE TITLE
pde files not parsing correctly

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#31]
The pde files should keep their underscore.  Examples/exercises with multiple PDEs are producing strange results.  For example:

http://learningprocessing.com/examples/chp09/example-09-10-array-interactive-objects/

<img width="611" alt="screen shot 2015-08-17 at 9 01 16 am" src="https://cloud.githubusercontent.com/assets/191758/9305337/91303a1a-44be-11e5-9900-7ee74f4efc67.png">

should be:

```
array_interactive_objects.pde        stripes.pde
```

**Comment by scottwooden** [comment]
Sorted
