### ISSUE TITLE
example / exercise "caption" vs instructions

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#41]
I like that any content on an exercise or example post shows up above the code.  However, some content is likely better positioned as a "caption" under the sketch itself.  See the following:

http://learningprocessing.com/examples/chp03/example-03-05-mouse-key-events/

Here, the text tells the user what to do in the sketch.  We could put this in the yaml stuff or I could say say to set with CSS:

``` html
<div id = "sketch_caption">
<p>Click the mouse to draw a rectangle. Press any key to erase the background.</p>
</div>
```

What do you think @scottwooden?

**Comment by scottwooden** [comment]
Yeah good plan I'll create a caption div and display it when the sketch has loaded. I guess add "sketch-caption" into YAML?

**Comment by scottwooden** [comment]
Okay that's in. Need attribute in YAML to pass in.

**Comment by shiffman** [comment]
This is all set now!
