### ISSUE TITLE
video annotation times should link to time in video?

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#44]

**Comment by scottwooden** [comment]
Resolved on previous issue

**Comment by shiffman** [comment]
Sorry, I think I wasn't clear about this one.  What I meant is that that if a user clicks on the annotations themselves (perhaps just the timestamp?) the video would "jump" to that moment in time (so the inverse).  This is lower priority and I can sort it out later if need be.

**Comment by scottwooden** [comment]
Oh yeah that should work too now! From the timestamp fix we should be good.

**Comment by shiffman** [comment]
oh right, yes, I see that now sorry!  I think the interaction is just a little unclear b/c I do not get the "clicking hand"?  Maybe we should explicitly link the timestamp?

**Comment by scottwooden** [comment]
Okay that's been done. Highlights and changes to pointer :)

**Comment by shiffman** [comment]
fantastic!
