### ISSUE TITLE
video annotations timing

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#45]
What should we do when the time for the annotation arrives?  Highlight it?  Should all the others be hidden, but you could click "view all annotations"?  Will there be many more annotations in the future? I'm open to all possibilities.  Since there are so few now, perhaps highlighting is best.

**Comment by scottwooden** [comment]
Yeah highlighting is something I originally put in and worked. It's playing up now for some reason! I'm not sure if it's something to do with popcorn.js or the seconds we're putting in to it. Will debug this after main issues have been sorted

**Comment by scottwooden** [comment]
This has been resolved. Woo! Now we need to format the Timestamps a certain way. See Chapter 0-5 of the video posts to see the required format.

**Comment by shiffman** [comment]
With some regex magic all timestamps are now "00:00" format.
