### ISSUE TITLE
video navigation error on number > 0

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#47]
When I click in the video nav on 0-0, 1-0, 2-0, etc. the navigation functions properly.  When I click on any other videos, there is a layout error:

<img width="408" alt="screen shot 2015-08-25 at 8 15 31 am" src="https://cloud.githubusercontent.com/assets/191758/9466253/85df814a-4b01-11e5-8709-908833d138b7.png">

**Comment by scottwooden** [comment]
Ah Yeah literally just fixed this. Pushing now

**Comment by shiffman** [comment]
Awesome, works!
