### ISSUE TITLE
landing page content starting far down the page in safari?

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#49]
<img width="1402" alt="screen shot 2015-08-25 at 9 55 09 am" src="https://cloud.githubusercontent.com/assets/191758/9468399/6fcdaed2-4b0f-11e5-99bc-9d7b9b052d4b.png">

Only on the landing page, not seeing this in chrome, only safari Version 8.0.7 (10600.7.12) on mac 10.10.4.

**Comment by scottwooden** [comment]
Fixed and pushed
