### ISSUE TITLE
640x360 sketches feel too big

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#6]
not sure if i just need to shrink them or if there is a design solution?

the larger sketches with white background and no border fit weirdly on page.

<img width="1521" alt="screen shot 2015-08-12 at 10 42 05 am" src="https://cloud.githubusercontent.com/assets/191758/9226925/e5348c1c-40de-11e5-910f-8754db14eb41.png">

**Comment by scottwooden** [comment]
Put a border on the left which creates a nice boundary I think! Also scrollable if user scrolls in that window.

**Comment by shiffman** [comment]
This looks good.  Is there an ideal size for sketches in your opinion?  I was thinking of shrinking them all a bit and trying 480 x 240?

**Comment by scottwooden** [comment]
480 would be awesome, if that's easy to do?

**Comment by shiffman** [comment]
Yup, it's a matter of doing a big find/replace, I'll take care of it.  For now I'm updating the one example that now renders on every page.

**Comment by scottwooden** [comment]
NICE. Perfect
