### ISSUE TITLE
links to international purchases?

### ISSUE THREAD

**Issue by shiffman** [shiffman/learningprocessing.com#7]
maybe we need a page that has links to various places to buy the book for non US customers.  this could be linked subtly from under the "order" button online?  Also, for digital versions?  

Also, no need for "pre-order" anymore!

**Comment by scottwooden** [comment]
Added a new page "Get the book" Where you can outline all other availabilities of the book. Populate it and I'll tweak design accordingly!

**Comment by shiffman** [comment]
now #17
